### ISSUE TITLE
Ranged mobs dont attack

### ISSUE THREAD

**Issue by SatyPardus** [ACID-Scripts/Classic#43]
Ranged mobs get the Event 20 set to 0 on aggro, but it get never set back to 1 on most ranged mobs.
That causes to a bug where the npc doesnt attack you on meele.

I fixed that by removing the event 20 at all mobs, where it doesnt get set back to 1 (But i think thats not a good fix, huh?)

**Comment by SatyPardus** [comment]
https://github.com/ACID-Scripts/Classic/commit/150451d9492a85b90cc6c4da4687b9617951a5ff
Was fixed with this commit. Thanks guys!

**Comment by cala** [comment]
You welcome. :)
