### ISSUE TITLE
Some more incorrect aggro texts

### ISSUE THREAD

**Issue by scotty0100** [ACID-Scripts/Classic#6]
This is the Gnoll aggro text for 'More bones to gnaw on...'

    SELECT * FROM `creature_ai_scripts` WHERE `action1_param1` = '-5' AND `event_type` = '4';

A few of these I believe to be incorrect (NPC name is in the comment column of this query):
Witherbark Axe Thrower
Syndicate Pathstalker
Kobold Digger
Venture Co Mechanic
Dark Iron Lookout

**Comment by xfurry** [comment]
Create pull request or patch please.

**Comment by cala** [comment]
Thank you. Fixed by https://github.com/ACID-Scripts/Classic/commit/d84cd53bcdf795d0787b2fc76ef6f937aee3a844
